matrix:
  include:
    - language: python
      sudo: required
      dist: trusty

      python: 3.5

      install:
        - pip3 install codecov pytest pytest-cov
        - ./utils/tests/jumspcale_install.sh
        - ./utils/tests/zrobot_install.sh

      script:
        - make test

      after_success:
        - codecov
